CREATE TABLE PARENT_TASK
(
ID NUMBER(15) NOT NULL,
TITLE VARCHAR2(100 CHAR)
);

ALTER TABLE PARENT_TASK ADD CONSTRAINT PARENT_TASK_PK PRIMARY KEY(ID);

CREATE TABLE TASK
(
ID NUMBER(15) NOT NULL,
TITLE VARCHAR2(100 CHAR),
SUMMARY VARCHAR2(500 CHAR),
START_DATE DATE,
END_DATE DATE,
PRIORITY NUMBER(3),
PARENT_TASK_ID NUMBER(15)
);

ALTER TABLE TASK ADD CONSTRAINT TASK_PK PRIMARY KEY(ID);

CREATE SEQUENCE TASK_SEQ START WITH 1 INCREMENT BY 1;