CREATE TABLE PARENT_TASK
(
ID NUMBER(15) NOT NULL,
TASK VARCHAR2(100)
);

ALTER TABLE PARENT_TASK ADD CONSTRAINT PARENT_TASK_PK PRIMARY KEY(ID);

CREATE TABLE TASK
(
ID NUMBER(15) NOT NULL AUTO_INCREMENT,
TASK VARCHAR2(100),
START_DATE TIMESTAMP,
END_DATE DATE,
PRIORITY NUMBER(3),
PARENT_TASK_ID NUMBER(15)
);

ALTER TABLE TASK ADD CONSTRAINT TASK_PK PRIMARY KEY(ID);