jenkinsPipeLine {

   stage('Step 1 : Git Checkout') {
     git credentialsId: 'Password', url: 'https://sathish102003@bitbucket.org/sathish102003/task_manager.git'
     echo 'Done : Git checkout'
   }

   stage('Step 2 : Build Image') {
      sh 'docker build -t sathish102003/task-ui-":$BUILD_NUMBER"'
   }

   stage('Step 3 : Deliver Image') {
	   	withCredentials([string(credentialsId: 'docker-pwd', variable: 'DockerPwd')]) {
	    	sh "docker login -u sathish102003 -p ${DockerPwd}"
		}
   		sh 'docker push sathish102003/task-ui-":$BUILD_NUMBER"'
   }

   stage('Step 4 : Run Image') {
      sh 'docker run --rm -d -p 8085:80/tcp --name task-ui-":$BUILD_NUMBER" task-ui-":$BUILD_NUMBER":latest'
   }
}
